config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'sign-in', to: 'auth#sign_in'
  post 'sign-in', to: 'auth#sign_in_submit'
  post 'sign-out', to: 'auth#sign_out'
  get 'sign-out', to: redirect('/', status: 302)
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_sign_in
  helper_method :signed_in?, :current_user

  def current_user
    return unless session[:user_id]

    @user = User.find(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  def require_sign_in
    redirect_to :sign_in unless signed_in?
  end
end

app/controllers/auth_controller.rb
# frozen_string_literal: true

class AuthController < ApplicationController
  skip_before_action :require_sign_in, only: %i[sign_in sign_in_submit]

  def sign_in
    @user = User.new
  end

  def sign_in_submit
    @user = User.find_or_initialize_by(username: user_params['username'])

    if @user&.authenticate(user_params[:password])
      session[:user_id] = @user.id
      return redirect_to root_path
    end

    flash.now[:alert] = translate('please_try_again')
    render :sign_in, status: :unprocessable_entity
  end

  def sign_out
    session[:user_id] = nil
    redirect_to root_path, status: :found
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :require_sign_in, only: %i[index]

  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'bg-success'
    when 'error'
      'bg-danger'
    when 'alert'
      'bg-warning'
    when 'notice'
      'bg-info'
    else
      flash_type.to_s
    end
  end
end

app/views/home/index.html.erb
  <%= render Home::TenorionComponent.new({}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>MusicGrid</title>
    <meta name="viewport" content="width=960, user-scalable=yes" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "/assets/assets/stylesheets/application.css", media: "all" %>
    <%= javascript_include_tag "/assets/javascript/entrypoints/application.js" %>
  </head>
  <body class="full-height d-flex align-items-stretch flex-column">
    <div class="w-100 d-flex flex-column align-items-center">
      <%= yield %>
      <div class="footer footer-elements d-flex align-items-spread justify-content-between">
        <a class="footer-elements border btn rounded-top btn-outline-secondary" href="https://github.com/Peregrine42">© 2023 Duncan Fermor</a>
        <% if not signed_in? %>
          <a class="footer-elements border btn rounded-top btn-outline-secondary text-align-right" href="/sign-in">Sign in</a>
        <% else %>
          <%= simple_form_for :session, :url => sign_out_path do %>
            <button class="footer-elements border btn rounded-top btn-outline-secondary text-align-right">Sign out</button>
          <% end %>
        <% end %>
      </div>
    </div>
  </body>
</html>